id = "pixelated_io"
name = "Pixelated IO Theme"
version = "0.0.1"
schema_version = 1
description = "Pixelated IO  Theme for Zed"
# repository = "https://github.com/anya-theme/anya-zed"
authors = ["Scott Alexander <scott@pixelated.io>"]
themes = ["themes/pixelated_io.json"]
languages = []

[lib]

[grammars]

[language_servers]
